#!/usr/bin/env python3
"""
extract_resume.py — Extract resume content from a PDF into the standardized
JSON schema, preserving inline <b> bold tags for keyword bolding.

Designed for PDFs generated by the Resume Generator skill (generate_resume.py),
but can work with conventionally structured resumes using Times or similar fonts.

Usage:
    python3 extract_resume.py <input.pdf> [output.json]

If output.json is omitted, the JSON is printed to stdout.

Dependencies:
    pip3 install pdfplumber
"""

import json
import re
import sys

import pdfplumber

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MONTH = (
    r"(?:January|February|March|April|May|June|July|August|September|"
    r"October|November|December)"
)

# Matches date ranges: "Month YYYY - Month YYYY" or "Month YYYY - Present"
DATE_RANGE_RE = re.compile(
    rf"({MONTH}\s+\d{{4}}\s*-\s*(?:Present|{MONTH}\s+\d{{4}}))"
)

# Matches a single trailing date: "Month YYYY"
DATE_SINGLE_RE = re.compile(rf"({MONTH}\s+\d{{4}})\s*$")

# Known section header names (uppercase, as they appear in the PDF)
SECTION_NAMES = {
    "SUMMARY",
    "WORK EXPERIENCE",
    "EXPERIENCE",
    "PROJECTS",
    "EDUCATION",
    "CERTIFICATIONS",
    "SKILLS",
}

# Structural bold threshold — section headers and the name line use a font
# size larger than body text. Anything above this is "structural" and should
# NOT be wrapped in <b> tags (those are reserved for keyword bolding).
STRUCTURAL_SIZE_THRESHOLD = 11.0

# Vertical tolerance (points) for grouping characters on the same line.
Y_TOLERANCE = 2.0


# ---------------------------------------------------------------------------
# 1. Low-level: character extraction → formatted lines
# ---------------------------------------------------------------------------


def extract_formatted_lines(pdf_path):
    """
    Extract every visual line from the PDF, reconstructing text with inline
    <b>…</b> tags wherever the original used a Bold font variant at body-text
    size.

    Returns a list of dicts:
        text      – line text with <b> tags for keyword bolding
        max_size  – largest font size on the line
        is_italic – True when the majority of visible chars use an italic font
        is_bullet – True when the line starts with a bullet character
    """
    all_lines = []

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            chars = page.chars
            if not chars:
                continue

            # ---- group characters into visual lines by y-coordinate ----
            groups = []
            current_group = []
            prev_top = None

            for c in chars:
                top = round(c["top"], 1)
                if prev_top is not None and abs(top - prev_top) >= Y_TOLERANCE:
                    if current_group:
                        groups.append(current_group)
                    current_group = []
                current_group.append(c)
                prev_top = top
            if current_group:
                groups.append(current_group)

            # ---- reconstruct each line with <b> tags ----
            for grp in groups:
                pieces = []
                in_bold = False
                sizes = []
                italic_count = 0
                total_visible = 0

                for ch in grp:
                    txt = ch["text"]
                    if txt == "(cid:127)":
                        txt = "\u2022"  # bullet character

                    font = ch["fontname"]
                    size = ch["size"]

                    if txt.strip():
                        sizes.append(size)
                        total_visible += 1
                        if "Italic" in font:
                            italic_count += 1

                    is_bold_font = "Bold" in font
                    is_structural = size > STRUCTURAL_SIZE_THRESHOLD

                    if is_bold_font and not is_structural:
                        if not in_bold:
                            pieces.append("<b>")
                            in_bold = True
                        pieces.append(txt)
                    else:
                        if in_bold:
                            pieces.append("</b>")
                            in_bold = False
                        pieces.append(txt)

                if in_bold:
                    pieces.append("</b>")

                line_text = "".join(pieces).strip()
                if not line_text:
                    continue

                all_lines.append(
                    {
                        "text": line_text,
                        "max_size": max(sizes) if sizes else 10.0,
                        "is_italic": (italic_count > 0)
                        if total_visible
                        else False,
                        "is_bullet": line_text.lstrip().startswith("\u2022"),
                    }
                )

    return all_lines


# ---------------------------------------------------------------------------
# 2. Section splitting
# ---------------------------------------------------------------------------


def _is_section_header(line):
    """True when the line matches a known section header (all-caps, large font)."""
    if line["max_size"] <= STRUCTURAL_SIZE_THRESHOLD:
        return False
    clean = re.sub(r"</?b>", "", line["text"]).strip()
    return clean.upper() in SECTION_NAMES


def split_into_sections(lines):
    """
    Return an ordered list of (section_name, [lines]) tuples.
    The first implicit section is always "HEADER" (name + contact row).
    """
    sections = []
    current_name = "HEADER"
    current_lines = []

    for ln in lines:
        if _is_section_header(ln):
            if current_lines:
                sections.append((current_name, current_lines))
            current_name = (
                re.sub(r"</?b>", "", ln["text"]).strip().upper()
            )
            current_lines = []
        else:
            current_lines.append(ln)

    if current_lines:
        sections.append((current_name, current_lines))

    return sections


# ---------------------------------------------------------------------------
# 3. Helpers
# ---------------------------------------------------------------------------


def _strip_bold(text):
    """Remove all <b></b> tags from text."""
    return re.sub(r"</?b>", "", text)


def _split_title_and_date(text):
    """
    Split a line like '<b>Title</b>Month YYYY - Month YYYY' into (title, dates).
    Handles both date ranges and single dates.
    """
    clean = _strip_bold(text)
    # Try range first
    m = DATE_RANGE_RE.search(clean)
    if m:
        return clean[: m.start()].strip(), m.group(1).strip()
    # Try single date
    m = DATE_SINGLE_RE.search(clean)
    if m:
        return clean[: m.start()].strip(), m.group(1).strip()
    return clean, ""


def _split_org_and_location(text):
    """Split 'Organization - City, Country' into (org, location)."""
    clean = _strip_bold(text).strip()
    parts = clean.rsplit(" - ", 1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return clean, ""


def _has_any_date(line):
    """True if the line text (stripped of tags) contains any date pattern."""
    clean = _strip_bold(line["text"])
    return bool(DATE_RANGE_RE.search(clean) or DATE_SINGLE_RE.search(clean))


def _collect_bullet(lines, start_idx):
    """
    Starting from a bullet line, collect the full bullet text including any
    continuation lines that wrap to the next visual line.
    Returns (full_text, next_index).
    """
    text = lines[start_idx]["text"].lstrip("\u2022 ").strip()
    idx = start_idx + 1
    while idx < len(lines):
        ln = lines[idx]
        # Stop if we hit another bullet, an italic org line, or a title+date line
        if ln["is_bullet"] or ln["is_italic"] or _has_any_date(ln):
            break
        # It's a continuation line
        text += " " + ln["text"].strip()
        idx += 1
    return text, idx


# ---------------------------------------------------------------------------
# 4. Section parsers
# ---------------------------------------------------------------------------


def parse_header(lines):
    """Parse HEADER section → contact dict."""
    contact = {"name": "", "email": "", "phone": "", "linkedin": "", "location": ""}
    if not lines:
        return contact

    # First line is the name
    contact["name"] = _strip_bold(lines[0]["text"]).strip()

    # Second line is |-separated contact details
    if len(lines) > 1:
        parts = lines[1]["text"].split("|")
        for part in parts:
            p = part.strip()
            if "@" in p:
                contact["email"] = p
            elif re.match(r"\(?\d{3}\)?[\s\-]?\d{3}[\s\-]?\d{4}", p):
                contact["phone"] = p
            elif "linkedin" in p.lower():
                contact["linkedin"] = p
            else:
                if contact["location"]:
                    contact["location"] += ", " + p
                else:
                    contact["location"] = p
    return contact


def parse_summary(lines):
    """Parse SUMMARY section → list of bullet strings (with <b> tags)."""
    bullets = []
    idx = 0
    while idx < len(lines):
        if lines[idx]["is_bullet"]:
            text, idx = _collect_bullet(lines, idx)
            bullets.append(text)
        else:
            # Non-bullet text — append to last bullet as continuation, or start new
            if bullets:
                bullets[-1] += " " + lines[idx]["text"].strip()
            else:
                bullets.append(lines[idx]["text"].strip())
            idx += 1
    return bullets


def parse_experience(lines):
    """Parse WORK EXPERIENCE section → list of experience entry dicts."""
    entries = []
    idx = 0

    while idx < len(lines):
        ln = lines[idx]

        # Detect a title + date line (bold structural title on body-size line with a date)
        if _has_any_date(ln) and not ln["is_bullet"] and not ln["is_italic"]:
            title, dates = _split_title_and_date(ln["text"])
            idx += 1

            # Next line is usually the italic company/location
            company, location = "", ""
            if idx < len(lines) and lines[idx]["is_italic"]:
                company, location = _split_org_and_location(lines[idx]["text"])
                idx += 1

            # Collect bullet points
            bullets = []
            while idx < len(lines):
                if lines[idx]["is_bullet"]:
                    text, idx = _collect_bullet(lines, idx)
                    bullets.append(text)
                elif (
                    not lines[idx]["is_italic"]
                    and not _has_any_date(lines[idx])
                ):
                    # Continuation of the last bullet
                    if bullets:
                        bullets[-1] += " " + lines[idx]["text"].strip()
                    idx += 1
                else:
                    break

            entries.append(
                {
                    "title": title,
                    "company": company,
                    "dates": dates,
                    "location": location,
                    "bullets": bullets,
                }
            )
        else:
            idx += 1

    return entries


def parse_projects(lines):
    """Parse PROJECTS section → list of project entry dicts."""
    entries = []
    idx = 0

    while idx < len(lines):
        ln = lines[idx]

        if _has_any_date(ln) and not ln["is_bullet"] and not ln["is_italic"]:
            name, dates = _split_title_and_date(ln["text"])
            idx += 1

            # Optional description (non-bullet, non-italic, non-date line)
            description = ""
            if (
                idx < len(lines)
                and not lines[idx]["is_bullet"]
                and not lines[idx]["is_italic"]
                and not _has_any_date(lines[idx])
            ):
                description = lines[idx]["text"].strip()
                idx += 1

            # Collect bullets
            bullets = []
            while idx < len(lines):
                if lines[idx]["is_bullet"]:
                    text, idx = _collect_bullet(lines, idx)
                    bullets.append(text)
                elif (
                    not lines[idx]["is_italic"]
                    and not _has_any_date(lines[idx])
                ):
                    if bullets:
                        bullets[-1] += " " + lines[idx]["text"].strip()
                    idx += 1
                else:
                    break

            entries.append(
                {
                    "name": name,
                    "dates": dates,
                    "description": description,
                    "bullets": bullets,
                }
            )
        else:
            idx += 1

    return entries


def parse_education(lines):
    """Parse EDUCATION section → list of education entry dicts."""
    entries = []
    idx = 0

    while idx < len(lines):
        ln = lines[idx]

        if _has_any_date(ln) and not ln["is_bullet"] and not ln["is_italic"]:
            degree, dates = _split_title_and_date(ln["text"])
            idx += 1

            school, location = "", ""
            if idx < len(lines) and (
                lines[idx]["is_italic"]
                or (
                    not lines[idx]["is_bullet"]
                    and not _has_any_date(lines[idx])
                )
            ):
                school, location = _split_org_and_location(lines[idx]["text"])
                idx += 1

            details = []
            while idx < len(lines):
                if lines[idx]["is_bullet"]:
                    text, idx = _collect_bullet(lines, idx)
                    details.append(text)
                else:
                    break

            entries.append(
                {
                    "degree": degree,
                    "school": school,
                    "dates": dates,
                    "location": location,
                    "details": details,
                }
            )
        else:
            idx += 1

    return entries


def parse_certifications(lines):
    """Parse CERTIFICATIONS section → list of certification entry dicts."""
    entries = []
    idx = 0

    while idx < len(lines):
        ln = lines[idx]

        if _has_any_date(ln) and not ln["is_bullet"]:
            name, date = _split_title_and_date(ln["text"])
            idx += 1

            # Next line is the issuer
            issuer = ""
            if idx < len(lines) and not _has_any_date(lines[idx]):
                issuer = _strip_bold(lines[idx]["text"]).strip()
                idx += 1

            entries.append(
                {
                    "name": name,
                    "date": date,
                    "issuer": issuer,
                }
            )
        else:
            idx += 1

    return entries


def parse_skills(lines):
    """
    Parse SKILLS section → list of {category, items} dicts.
    Expected format: '<b>Category:</b> item1, item2, item3'
    """
    categories = []

    # Join all lines into a single string to handle wrapping
    full_text = " ".join(ln["text"] for ln in lines)

    # Split on bold category labels:  <b>Category:</b>
    parts = re.split(r"<b>([^<]+?):</b>\s*", full_text)

    # parts = ["", "Category1", "items...", "Category2", "items...", ...]
    i = 1
    while i < len(parts) - 1:
        category = parts[i].strip()
        items_text = _strip_bold(parts[i + 1]).strip()
        items = [item.strip() for item in items_text.split(",") if item.strip()]
        categories.append(
            {
                "category": category,
                "items": items,
            }
        )
        i += 2

    return categories


# ---------------------------------------------------------------------------
# 5. Main pipeline
# ---------------------------------------------------------------------------


def extract_resume_to_json(pdf_path):
    """Full pipeline: PDF → standardized JSON schema dict."""
    lines = extract_formatted_lines(pdf_path)
    sections = split_into_sections(lines)

    resume = {}

    for name, sec_lines in sections:
        if name == "HEADER":
            resume["contact"] = parse_header(sec_lines)
        elif name == "SUMMARY":
            resume["summary"] = parse_summary(sec_lines)
        elif name in ("WORK EXPERIENCE", "EXPERIENCE"):
            resume["experience"] = parse_experience(sec_lines)
        elif name == "PROJECTS":
            resume["projects"] = parse_projects(sec_lines)
        elif name == "EDUCATION":
            resume["education"] = parse_education(sec_lines)
        elif name == "CERTIFICATIONS":
            resume["certifications"] = parse_certifications(sec_lines)
        elif name == "SKILLS":
            resume["skills"] = parse_skills(sec_lines)

    return resume


def main():
    if len(sys.argv) < 2:
        print(
            f"Usage: python3 {sys.argv[0]} <input.pdf> [output.json]",
            file=sys.stderr,
        )
        sys.exit(1)

    pdf_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None

    resume = extract_resume_to_json(pdf_path)
    json_str = json.dumps(resume, indent=2, ensure_ascii=False)

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(json_str + "\n")
        print(f"✓ Extracted to: {output_path}", file=sys.stderr)
    else:
        print(json_str)


if __name__ == "__main__":
    main()
